server {
    listen 80;
    server_name tools.woodpilot.fr;
    root /usr/share/nginx/html;
    index index.html;
    server_tokens off;
    add_header X-Content-Type-Options nosniff always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;
    add_header X-Frame-Options SAMEORIGIN always;
    location / {
        try_files $uri $uri/ =404;
        expires -1;
    }
    location ~ \.md$ { return 404; }
}
