import test from 'node:test';
import assert from 'node:assert/strict';
import {keepScreenAwake} from '../public/woodpilot-mobile/screen-awake.js';
const tick=()=>new Promise(resolve=>setImmediate(resolve));
function setup(request){const doc=new EventTarget();doc.visibilityState='visible';const win=new EventTarget(),states=[];return {doc,win,states,controller:keepScreenAwake({doc,win,nav:{wakeLock:{request}},onStatus:s=>states.push(s)})};}
function sentinel(){const lock=new EventTarget();lock.released=false;lock.release=async()=>{lock.released=true;lock.dispatchEvent(new Event('release'));};return lock;}
test('Écran : un seul verrou, libération en arrière-plan et retour visible',async()=>{const locks=[];const s=setup(async type=>{assert.equal(type,'screen');const lock=sentinel();locks.push(lock);return lock;});await tick();s.doc.dispatchEvent(new Event('pointerdown'));await tick();assert.equal(locks.length,1);s.doc.visibilityState='hidden';s.doc.dispatchEvent(new Event('visibilitychange'));assert.equal(locks[0].released,true);s.doc.visibilityState='visible';s.doc.dispatchEvent(new Event('visibilitychange'));await tick();assert.equal(locks.length,2);assert.equal(s.states.at(-1),'active');s.controller.dispose();assert.equal(locks[1].released,true);});
test('Écran : refus du système sans erreur, nouvel essai au toucher',async()=>{let count=0;const s=setup(async()=>{if(++count===1)throw new Error('low battery');return sentinel();});await tick();assert.equal(s.states.at(-1),'unavailable');s.doc.dispatchEvent(new Event('pointerdown'));await tick();assert.equal(s.states.at(-1),'active');s.controller.dispose();});
test('Écran : requête tardive après fermeture libérée immédiatement',async()=>{let resolve;const lock=sentinel();const s=setup(()=>new Promise(r=>resolve=r));s.win.dispatchEvent(new Event('pagehide'));resolve(lock);await tick();assert.equal(lock.released,true);assert.ok(!s.states.includes('active'));s.controller.dispose();});
test('Écran : navigateur incompatible explicite',()=>{const doc=new EventTarget();doc.visibilityState='visible';const states=[];const c=keepScreenAwake({doc,win:new EventTarget(),nav:{},onStatus:s=>states.push(s)});assert.deepEqual(states,['unsupported']);c.dispose();});
